"""Núcleo da aplicação Fato ou Fake."""

from .chunking import (
    ChunkingConfig,
    ChunkingError,
    EvidenceChunk,
    chunk_article_content,
)
from .crossref import (
    CrossrefClient,
    CrossrefError,
    CrossrefNotFoundError,
    CrossrefWork,
    IdentityVerification,
    verify_publication_identity,
    verify_publications,
)
from .evidence_extraction import (
    ClaimEvidencePair,
    EvidenceStatement,
    ExtractionConfig,
    build_claim_evidence_pairs,
    extract_evidence_statements,
)
from .evidence_classification import (
    DEFAULT_NLI_MODEL,
    ClassificationConfig,
    EvidenceAssessment,
    NliClassifier,
    RelationLabel,
    RelationProbabilities,
    TransformersNliClassifier,
    classify_claim_evidence_pairs,
)
from .input_validation import AnalysisInput, InputValidationError, validate_analysis_input
from .hybrid_retrieval import (
    HybridConfig,
    HybridIndex,
    HybridRetrievedChunk,
    RankedResult,
    RetrievalIndex,
)
from .pmc import (
    ArticleContent,
    ContentRetrievalError,
    ContentSection,
    PmcClient,
    retrieve_article_content,
)
from .search_preparation import (
    QueryPlanner,
    SearchPlan,
    SearchPreparationError,
    prepare_search_plan,
)
from .semantic_retrieval import (
    DEFAULT_EMBEDDING_MODEL,
    EmbeddingEncoder,
    SemanticIndex,
    SemanticRetrievedChunk,
    SentenceTransformerEncoder,
)
from .pubmed import (
    Publication,
    PubMedClient,
    PubMedError,
    PubMedSearchResult,
    QueryResult,
    search_pubmed,
)
from .retrieval import (
    Bm25Config,
    Bm25Index,
    RetrievalError,
    RetrievedChunk,
    tokenize,
)

__all__ = [
    "AnalysisInput",
    "ArticleContent",
    "Bm25Config",
    "Bm25Index",
    "ChunkingConfig",
    "ChunkingError",
    "ClaimEvidencePair",
    "ContentRetrievalError",
    "ContentSection",
    "CrossrefClient",
    "CrossrefError",
    "CrossrefNotFoundError",
    "CrossrefWork",
    "DEFAULT_NLI_MODEL",
    "DEFAULT_EMBEDDING_MODEL",
    "EmbeddingEncoder",
    "EvidenceStatement",
    "EvidenceAssessment",
    "ClassificationConfig",
    "ExtractionConfig",
    "EvidenceChunk",
    "HybridConfig",
    "HybridIndex",
    "HybridRetrievedChunk",
    "IdentityVerification",
    "InputValidationError",
    "NliClassifier",
    "PmcClient",
    "Publication",
    "PubMedClient",
    "PubMedError",
    "PubMedSearchResult",
    "QueryPlanner",
    "QueryResult",
    "RankedResult",
    "RetrievalError",
    "RetrievedChunk",
    "RetrievalIndex",
    "RelationLabel",
    "RelationProbabilities",
    "SearchPlan",
    "SearchPreparationError",
    "SemanticIndex",
    "SemanticRetrievedChunk",
    "SentenceTransformerEncoder",
    "TransformersNliClassifier",
    "prepare_search_plan",
    "build_claim_evidence_pairs",
    "classify_claim_evidence_pairs",
    "chunk_article_content",
    "retrieve_article_content",
    "search_pubmed",
    "tokenize",
    "validate_analysis_input",
    "verify_publication_identity",
    "verify_publications",
    "extract_evidence_statements",
]
